
name: Continous Intergration

on:
  push:
    branches:
    - master
    - v2
  pull_request:
    branches:
    - master
    - v2

jobs:
  #### docker hub image registry pipeline
  build-image-dockerhub:
    permissions: 
      contents: read
    runs-on: ubuntu-latest
    # needs: checkup
    steps:
      # - name: Download Build Artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: build
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: DEBUG
        run: |
          echo `ls`
          echo `pwd`

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Build and test
      #   uses: docker/build-push-action@v6
      #   with:
      #     target: build

      #     load: true
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          # context: "{{defaultContext}}:build"
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/portfolio:latest
          # tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

