name: Release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # utilise node
      - name: Use Node.js  22
        uses: actions/setup-node@v4
        with:
          node-version: 22


      - name: Clean install NPM
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Execute semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}